### ISSUE TITLE
MonoAndroid v10 required

### ISSUE THREAD

**Issue by ahmad913** [Baseflow/ExoPlayerXamarin#100]
## 🐛 Bug Report

Getting the following error when trying to update my package from 2.9.8 to 2.11.3
NU1202	Package Xam.Plugins.Android.ExoPlayer 2.11.3 is not compatible with monoandroid90 (MonoAndroid,Version=v9.0). Package Xam.Plugins.Android.ExoPlayer 2.11.3 supports: monoandroid10.0 (MonoAndroid,Version=v10.0)

tried to change my targeted framework from the Android Projects properties, but the same error is still showing again

### Expected behavior
download the package after changing the framework...

### Reproduction steps
not sure why/how but i can definitely reproduce it by trying to update the package.

### Configuration
Visual studio 2019
idk what info you need, but if you need more info @me

**Version:** 2.9.8

**Platform:** 
- [ ] :iphone: iOS
+ [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
You need to set both compile and target framework to Android 10. Also you need to make sure you have the SDK for it installed.
