### ISSUE TITLE
connecting a player to a playerview

### ISSUE THREAD

**Issue by ahmad913** [Baseflow/ExoPlayerXamarin#101]
## 🔙 Regression

in the original docs of the exo player you can connect the player to ther player view using this line
playerView.setPlayer(player);
however in the xamarin version we used to do it like this
_playerView = new SimpleExoPlayerView(Context) { Player = _player };
and since the 2.11.3 update the Player property is gone
so neither of them is available right now...

### Old (and correct) behavior
used to set the _playerView.Player = _player;
and it used to work.
### Current behavior
now the _playerView.Player property is unavailable
### Configuration

**Version:** 2.11.3

**Platform:** 
- [ ] :iphone: iOS
+ [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by rafaelSilva12** [comment]
Having the same problem , since playerView.Player is gone what should we use?

**Comment by martijn00** [comment]
Fixed in new release
