### ISSUE TITLE
AbstractMethodError when adding a listener to a SimpleExoPlayer

### ISSUE THREAD

**Issue by TGMM** [Baseflow/ExoPlayerXamarin#105]
The full error is:
`Java.Lang.AbstractMethodError: 'abstract method "void com.google.android.exoplayer2.Player$EventListener.onTimelineChanged(com.google.android.exoplayer2.Timeline, int)"'`

It appears when I invoke the activity where the player is situated, everything works fine if the player has no listener.

My listener code is:
```
    public class ExoPlayerEventListener : Object, IPlayerEventListener
    {
        private readonly VideoPlayer _activity;

        public ExoPlayerEventListener(VideoPlayer activity)
        {
            _activity = activity;
        }
    }
```
And it's added like so:
`_player.AddListener(new ExoPlayerEventListener(this));`

I'm using d8 and r8 with aapt2.
I've tried this and the one on the [Samples ](https://github.com/Baseflow/ExoPlayerXamarin/blob/develop/Samples/Main/PlayerActivity.cs#L736) page (which is practically the same) but to no avail.
Any help is appreciated, thanks in advance.

EDIT: Works fine in version 2.9.8

**Comment by bradlak** [comment]
The same issue here.

**Comment by martijn00** [comment]
Please try again in 2.11.7

**Comment by PawKanarek** [comment]
There is still something wrong with that listener... look at https://github.com/Baseflow/ExoPlayerXamarin/issues/112
