### ISSUE TITLE
Resource exo_progress_placeholder not found

### ISSUE THREAD

**Issue by NVFedorov** [Baseflow/ExoPlayerXamarin#106]
## 🐛 Bug Report

I'm trying to implement full screen feature. I added exo_playback_control_view.xml layout with the following content:

        <LinearLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:tools="http://schemas.android.com/tools"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom"
        android:layoutDirection="ltr"
        android:background="#CC000000"
        android:orientation="vertical"
        tools:targetApi="28">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:gravity="center"
            android:paddingTop="4dp"
            android:orientation="horizontal">

            <ImageButton
                android:id="@id/exo_prev"
                android:layout_width="50dp"
                android:layout_height="50dp"
                android:layout_gravity="center"
                android:adjustViewBounds="true"
                android:scaleType="fitCenter"
                style="@style/ExoMediaButton.Previous"/>

            <ImageButton
                android:id="@id/exo_rew"
                android:layout_width="50dp"
                android:layout_height="50dp"
                android:layout_gravity="center"
                android:adjustViewBounds="true"
                android:scaleType="fitCenter"
                style="@style/ExoMediaButton.Rewind"/>

            

            <ImageButton
                android:id="@id/exo_play"
                android:layout_width="50dp"
                android:layout_height="50dp"
                android:layout_gravity="center"
                android:adjustViewBounds="true"
                android:scaleType="fitCenter"
                style="@style/ExoMediaButton.Play"/>

            <ImageButton
                android:id="@id/exo_pause"
                android:layout_width="50dp"
                android:layout_height="50dp"
                android:layout_gravity="center"
                android:adjustViewBounds="true"
                android:scaleType="fitCenter"
                style="@style/ExoMediaButton.Pause"/>

            <ImageButton
                android:id="@id/exo_ffwd"
                android:layout_width="50dp"
                android:layout_height="50dp"
                android:layout_gravity="center"
                android:adjustViewBounds="true"
                android:scaleType="fitCenter"
                style="@style/ExoMediaButton.FastForward"/>

            <ImageButton
                android:id="@id/exo_next"
                android:layout_width="50dp"
                android:layout_height="50dp"
                android:layout_gravity="center"
                android:adjustViewBounds="true"
                android:scaleType="fitCenter"
                style="@style/ExoMediaButton.Next"/>

            

        </LinearLayout>

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="4dp"
            android:gravity="center_vertical"
            android:orientation="horizontal">

            <TextView
                android:id="@id/exo_position"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:textSize="14sp"
                android:textStyle="bold"
                android:paddingLeft="4dp"
                android:paddingRight="4dp"
                android:includeFontPadding="false"
                android:textColor="#FFBEBEBE"/>

            <View
                android:id="@id/exo_progress_placeholder"
                android:layout_width="0dp"
                android:layout_weight="1"
                android:layout_height="26dp"/>

            <TextView
                android:id="@id/exo_duration"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:textSize="14sp"
                android:textStyle="bold"
                android:paddingLeft="4dp"
                android:paddingRight="4dp"
                android:includeFontPadding="false"
                android:textColor="#FFBEBEBE"/>

            <FrameLayout
                android:id="@+id/exo_fullscreen_button"
                android:layout_width="32dp"
                android:layout_height="32dp"
                android:layout_gravity="right">

                <ImageView
                    android:id="@+id/exo_fullscreen_icon"
                    android:layout_width="18dp"
                    android:layout_height="18dp"
                    android:layout_gravity="center"
                    android:adjustViewBounds="true"
                    android:scaleType="fitCenter"
                    android:src="@drawable/ic_fullscreen_expand"/>

            </FrameLayout>
        </LinearLayout>

    </LinearLayout>

When I'm trying to build the project I'm getting the follwing errors:

    failed linking file resources.	ExoPlayerVU.Android
    resource id/exo_progress_placeholder (aka com.companyname.exoplayervu:id/exo_progress_placeholder) not found.

If I delete exo_progress_placeholder view it works fine. Is this view missing in bindings?

### Expected behavior
Project builds without errors.
### Reproduction steps
Add the exo_playback_control_view.xml layout and try to build the demo project.
### Configuration

**Version:** 
Xam.Plugins.Android.ExoPlayer 2.9.8
Xam.Plugins.Android.ExoPlayer.UI 2.9.8

**Platform:** 
- [x ] :robot: Android

    Xamarin   16.5.000.533 
    Xamarin Designer   16.5.0.470 
    Xamarin Templates   16.5.49
    Xamarin.Android SDK   10.2.0.100

**Comment by geo-bursuc** [comment]
> ## 🐛 Bug Report
> I'm trying to implement full screen feature. I added exo_playback_control_view.xml layout with the following content:
> 
> ```
>     <LinearLayout
>     xmlns:android="http://schemas.android.com/apk/res/android"
>     xmlns:tools="http://schemas.android.com/tools"
>     android:layout_width="match_parent"
>     android:layout_height="wrap_content"
>     android:layout_gravity="bottom"
>     android:layoutDirection="ltr"
>     android:background="#CC000000"
>     android:orientation="vertical"
>     tools:targetApi="28">
> 
>     <LinearLayout
>         android:layout_width="match_parent"
>         android:layout_height="wrap_content"
>         android:gravity="center"
>         android:paddingTop="4dp"
>         android:orientation="horizontal">
> 
>         <ImageButton
>             android:id="@id/exo_prev"
>             android:layout_width="50dp"
>             android:layout_height="50dp"
>             android:layout_gravity="center"
>             android:adjustViewBounds="true"
>             android:scaleType="fitCenter"
>             style="@style/ExoMediaButton.Previous"/>
> 
>         <ImageButton
>             android:id="@id/exo_rew"
>             android:layout_width="50dp"
>             android:layout_height="50dp"
>             android:layout_gravity="center"
>             android:adjustViewBounds="true"
>             android:scaleType="fitCenter"
>             style="@style/ExoMediaButton.Rewind"/>
> 
>         
> 
>         <ImageButton
>             android:id="@id/exo_play"
>             android:layout_width="50dp"
>             android:layout_height="50dp"
>             android:layout_gravity="center"
>             android:adjustViewBounds="true"
>             android:scaleType="fitCenter"
>             style="@style/ExoMediaButton.Play"/>
> 
>         <ImageButton
>             android:id="@id/exo_pause"
>             android:layout_width="50dp"
>             android:layout_height="50dp"
>             android:layout_gravity="center"
>             android:adjustViewBounds="true"
>             android:scaleType="fitCenter"
>             style="@style/ExoMediaButton.Pause"/>
> 
>         <ImageButton
>             android:id="@id/exo_ffwd"
>             android:layout_width="50dp"
>             android:layout_height="50dp"
>             android:layout_gravity="center"
>             android:adjustViewBounds="true"
>             android:scaleType="fitCenter"
>             style="@style/ExoMediaButton.FastForward"/>
> 
>         <ImageButton
>             android:id="@id/exo_next"
>             android:layout_width="50dp"
>             android:layout_height="50dp"
>             android:layout_gravity="center"
>             android:adjustViewBounds="true"
>             android:scaleType="fitCenter"
>             style="@style/ExoMediaButton.Next"/>
> 
>         
> 
>     </LinearLayout>
> 
>     <LinearLayout
>         android:layout_width="match_parent"
>         android:layout_height="wrap_content"
>         android:layout_marginTop="4dp"
>         android:gravity="center_vertical"
>         android:orientation="horizontal">
> 
>         <TextView
>             android:id="@id/exo_position"
>             android:layout_width="wrap_content"
>             android:layout_height="wrap_content"
>             android:textSize="14sp"
>             android:textStyle="bold"
>             android:paddingLeft="4dp"
>             android:paddingRight="4dp"
>             android:includeFontPadding="false"
>             android:textColor="#FFBEBEBE"/>
> 
>         <View
>             android:id="@id/exo_progress_placeholder"
>             android:layout_width="0dp"
>             android:layout_weight="1"
>             android:layout_height="26dp"/>
> 
>         <TextView
>             android:id="@id/exo_duration"
>             android:layout_width="wrap_content"
>             android:layout_height="wrap_content"
>             android:textSize="14sp"
>             android:textStyle="bold"
>             android:paddingLeft="4dp"
>             android:paddingRight="4dp"
>             android:includeFontPadding="false"
>             android:textColor="#FFBEBEBE"/>
> 
> 
>         <FrameLayout
>             android:id="@+id/exo_fullscreen_button"
>             android:layout_width="32dp"
>             android:layout_height="32dp"
>             android:layout_gravity="right">
> 
>             <ImageView
>                 android:id="@+id/exo_fullscreen_icon"
>                 android:layout_width="18dp"
>                 android:layout_height="18dp"
>                 android:layout_gravity="center"
>                 android:adjustViewBounds="true"
>                 android:scaleType="fitCenter"
>                 android:src="@drawable/ic_fullscreen_expand"/>
> 
>         </FrameLayout>
>     </LinearLayout>
> 
> </LinearLayout>
> ```
> 
> When I'm trying to build the project I'm getting the follwing errors:
> 
> ```
> failed linking file resources.	ExoPlayerVU.Android
> resource id/exo_progress_placeholder (aka com.companyname.exoplayervu:id/exo_progress_placeholder) not found.
> ```
> 
> If I delete exo_progress_placeholder view it works fine. Is this view missing in bindings?
> 
> ### Expected behavior
> Project builds without errors.
> 
> ### Reproduction steps
> Add the exo_playback_control_view.xml layout and try to build the demo project.
> 
> ### Configuration
> **Version:**
> Xam.Plugins.Android.ExoPlayer 2.9.8
> Xam.Plugins.Android.ExoPlayer.UI 2.9.8
> 
> **Platform:**
> 
> * [x ] 🤖 Android
>   Xamarin   16.5.000.533
>   Xamarin Designer   16.5.0.470
>   Xamarin Templates   16.5.49
>   Xamarin.Android SDK   10.2.0.100


Replace the placeholder with the following:

```
<com.google.android.exoplayer2.ui.DefaultTimeBar
android:id="@id/exo_progress"
android:layout_width="0dp"
android:layout_weight="1"
android:layout_height="26dp"/>
```

Solution found here: https://github.com/google/ExoPlayer/issues/6506

Explanation found here: https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/PlayerControlView.html
```
"exo_progress_placeholder - A placeholder that's replaced with the inflated DefaultTimeBar. Ignored if an exo_progress view exists."
```

**Comment by martijn00** [comment]
Please try again in 2.11.7
