### ISSUE TITLE
System.TypeLoadException when using PlayerNotificationManager.IMediaDescriptionAdapter

### ISSUE THREAD

**Issue by szymonkalista** [Baseflow/ExoPlayerXamarin#107]
## 🐛 Bug Report

Application crashes when class that implements interface:
`PlayerNotificationManager.IMediaDescriptionAdapter`
is being instantiated.

Exception that is thrown:
`
Could not load type 'Com.Google.Android.Exoplayer2.UI.PlayerNotificationManager.IMediaDescriptionAdapter' from assembly 'ExoPlayer.UI, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
`

Other interfaces provided by PlayerNotificationManager present the same behaviour.

Possibly some other nested types may also cause the app to crash when implemented or referenced, might be worth checking.

### Expected behavior

It would be cool, if it wouldn't crash. :~D

### Reproduction steps
Try to run the attached project on a physical android device or on an emulator.
1. Build and Run the application.
2. During deployment to the device exception should be thrown.

[ExoTest.zip](https://github.com/Baseflow/ExoPlayerXamarin/files/4678003/ExoTest.zip)

### Configuration
Android 9
**Version:**
2.11.4
**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [X] :monkey: Xamarin.Forms

**Comment by archangelnl** [comment]
I can definitively confirm that I'm getting the same Exception thrown on the latest version of Exoplayer with Android 10 as well.. Would be nice indeed if it didn't crash but oh well.

**Comment by archangelnl** [comment]
Still seems to be an issue on 2.11.6 combined with the latest version of XamarinMediaManager (0.9.9)

@martijn00 Could you have a look at this?

**Comment by martijn00** [comment]
It works fine here: https://github.com/Baseflow/XamarinMediaManager/blob/70afbdb223d6377f8648cb9f3f9c873946a506df/MediaManager/Platforms/Android/Media/MediaDescriptionAdapter.cs#L13

You need to enable C#8 and target Android 10 with AndroidX

**Comment by archangelnl** [comment]
Could this be re-opened? I'm still getting the same exception with the sample below (Which is based off of the sample with the original issue's sample, just updated to 2.11.6 and c#8 enabled)

[ExoTest.zip](https://github.com/Baseflow/ExoPlayerXamarin/files/4896606/ExoTest.zip)

**Comment by szymonkalista** [comment]
Same here.
These are the settings, that I've set. I guess this should do the trick, but doesn't. Also AndroidX seems to be turned on - screenshot which shows that MainActivity inherits from AndroidX.[...].

This is a clean Forms project, only exoplayer was added.


<img width="963" alt="Screenshot 2020-07-02 at 23 07 34" src="https://user-images.githubusercontent.com/17805617/87165494-847a2080-c2ca-11ea-96ad-b773569aaa0e.png">
<img width="958" alt="Screenshot 2020-07-02 at 23 08 21" src="https://user-images.githubusercontent.com/17805617/87165504-87751100-c2ca-11ea-913d-1dd3db7d5d2e.png">
<img width="962" alt="Screenshot 2020-07-02 at 23 09 18" src="https://user-images.githubusercontent.com/17805617/87165506-880da780-c2ca-11ea-9067-f8fde2bb84f9.png">
<img width="962" alt="Screenshot 2020-07-02 at 23 10 50" src="https://user-images.githubusercontent.com/17805617/87165508-88a63e00-c2ca-11ea-8bef-e1078685995d.png">
<img width="1691" alt="Screenshot 2020-07-02 at 23 23 11" src="https://user-images.githubusercontent.com/17805617/87165509-893ed480-c2ca-11ea-8c72-95007bf8cc40.png">

**Comment by martijn00** [comment]
If you want me to look into this you can make a PR or send me an email for commercial support.

**Comment by ToBeHonest** [comment]
Hi @martijn00 . I'm a bit confused about your approach. 
Maybe this and other interfaces that can't be instantiated are part of commercial support. In such case, you should state it clearly in README so that everyone can make conscious decision if want to use your software or not.
Apart form that if you can't provide working instructions how to run your software, why would I pay you for commercial support? This doesn't add up for me.
Either way everyone would want to know if this is paid feature or you have no idea how to fix it because it simply works for you.

**Comment by szymonkalista** [comment]
I've looked some more into this. It seems that (at least on my mac) there is some issue during type loading.

In RuntimeTypeHandle.cs line 342 (This file comes from mono), there is: 

```
var t = internal_from_name (typeName, ref stackMark, null, throwOnError, ignoreCase, false);
if (throwOnError && t == null)
	throw new TypeLoadException ("Error loading '" + typeName + "'");
```

So in my case on macOS, some interfaces that are nested in PlayerNotificationManager have typeName that follows the following convention:
`
Com.Google.Android.Exoplayer2.UI.PlayerNotificationManager/NESTED_INTERFACE, ExoPlayer.UI
`
for example:
`
Com.Google.Android.Exoplayer2.UI.PlayerNotificationManager/ICustomActionReceiverInvoker, ExoPlayer.UI
`
but for PlayerNotificationManager.IMediaDescriptionAdapter it looks like this:
`Com.Google.Android.Exoplayer2.UI.PlayerNotificationManager.IMediaDescriptionAdapter, ExoPlayer.UI`
and this part causes the exception to be thrown.

After changing it to:
`
Com.Google.Android.Exoplayer2.UI.PlayerNotificationManager/IMediaDescriptionAdapter, ExoPlayer.UI
`
during debug, application runs as expected and notification is shown.

I guess this can be changed in `ExoPlayer.UI/Transforms/Metadata.xml` but I am not really sure how to do it right now.
I can try to create a PR with a fix, but I have to read some more about java bindings.

Also this seems to be the same thing happening, but to the other interface:
#108
