### ISSUE TITLE
[Android]IVideoListener not working as intended

### ISSUE THREAD

**Issue by Mandrakia** [Baseflow/ExoPlayerXamarin#109]
## 🐛 Bug Report

The implementation of VideoListeners doesn't work in the current version.
By doing player.AddVideoListener(this); It will make the app crash on runtime.

Strange thing is there's nothing to implement from IVideoListener despite it being an interface.

### Expected behavior
No crash and interface methods called.

### Reproduction steps
Setup a player , source etc..
Add a video Listener (player.AddVideoListener()) and test.

**Comment by martijn00** [comment]
Please try again in 2.11.7
