### ISSUE TITLE
How to use ffmepg extension

### ISSUE THREAD

**Issue by earkania** [Baseflow/ExoPlayerXamarin#111]
# 💬 Questions and Help
Hi. I'm using ExoPlayerXamarin in my project and everything is OK. But on some devices there is not supported playing mpeg2 audio at hardware level. I know Exoplayer supports playing some audio formats using ffmpeg plugin. But I can't figure out how to use this plugin with ExoPlayerXamarin. I have initialized DefaultRenderersFactory  like this:
`
   DefaultRenderersFactory renderersFactory = new DefaultRenderersFactory(this);
   renderersFactory.SetExtensionRendererMode(DefaultRenderersFactory.ExtensionRendererModePrefer);
`
But it simply does not have any effect.
Can you please guide me how to use ffmpeg extension.

**Comment by milouz-corp** [comment]
I have the same issue, did you find any solution ?

**Comment by milouz-corp** [comment]
Thank you very much for that reply. I wasn't expecting such a quick and detailed message after two years. I am even surprised to receive an answer. ;-)

In my case, I discover that I can play a video in H265/AC3(5.1) on an Amazon firestick without further tweak, (it depends on the hardware). So I may avoid doing the process you describe, but it's good to known there is a solution. I may have a look later.

Thanks again and I hope this helps others.
