### ISSUE TITLE
MAUI Support?

### ISSUE THREAD

**Issue by MichaelPeter** [Baseflow/ExoPlayerXamarin#119]
## 🚀 Feature Requests

Are there plans to include cross project support for Microsoft MAUI?

### Platforms affected (mark all that apply)
- [ X] :iphone: iOS
- [ X] :robot: Android
- [X] :checkered_flag: WPF
- [ X] :earth_americas: UWP
- [ X] :apple: MacOS
- [ ] :tv: tvOS
- [ X] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Exoplayer is only available on Android
