### ISSUE TITLE
AnalyticsListener missing

### ISSUE THREAD

**Issue by gleblebedev** [Baseflow/ExoPlayerXamarin#120]
## 🚀 Feature Requests

Any chance to bring AnalyticsListener in?

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Please open a PR to add this to the bindings
