### ISSUE TITLE
Class SimpleExoPlayer is not reconized

### ISSUE THREAD

**Issue by moraesvi** [Baseflow/ExoPlayerXamarin#123]
## 💬 Class SimpleExoPlayer is not reconized

Hi, when I've updated to lasted version I can't build my application more.
The class SimpleExoPlayer is not reconized.

**Comment by nafr1** [comment]
> ## 💬 Class SimpleExoPlayer is not reconized
> Hi, when I've updated to lasted version I can't build my application more. The class SimpleExoPlayer is not reconized.

Same issue... were you able to find a solution? I can't even find ExoPlayer class since SimpleExoPlayer has been deprecated.

**Comment by martijn00** [comment]
It seems the class has an error when trying to bind the ExoPlayer class. I can't find a fix for it yet.

**Comment by moraesvi** [comment]
Please, martijn can we have another class name with same methods ?
Another way to access ExoPlayer class
