### ISSUE TITLE
'SimpleCache' does not contain a constructor

### ISSUE THREAD

**Issue by jerry08** [Baseflow/ExoPlayerXamarin#131]
The java source files in Google ExoPlayer has a constructor for 'SimpleCache' but the Xamarin bindings fails to create the constructor apparently. I can't use 'SimpleCache' to cache my videos.

**Comment by ArchangelWTF** [comment]
Yeah, some stuff is bound to not have bindings due to it having been removed for ease of getting the rest of Exo to bind correctly. I've fixed this in my PR so it should be usable.

**Comment by jerry08** [comment]
Thanks! It's working now. I hope they merge the PR and update the nuget package soon. That would make it easier for me to use in my public project.

**Comment by ArchangelWTF** [comment]
@martijn00 Could you close this as resolved and merge the PR? Thanks!

**Comment by ScriptSun** [comment]
@martijn00 any update coming soon? on the NuGet packages

**Comment by martijn00** [comment]
@ScriptSun what do you mean? I updated it 3 days ago: https://www.nuget.org/packages/Xam.Plugins.Android.ExoPlayer/2.18.4

**Comment by ScriptSun** [comment]
@martijn00  Thank you, is the SDK android 33 a bit early as i saw you targeted all the Exoplayer to 33, I don't think all of us are still ready to move especially since the android company will make it available for 2020 devices on the 20th of december.

If I change it to android 12 will your assemblies work or its a requirement of exoplayer last update

**Comment by ArchangelWTF** [comment]
@ScriptSun It's not really a requirement, I assume Martijn just moves to the latest targets for simplicity.. What I've done in an upcoming PR is I'm targeting some of the older MAUI targets that are still allowed by the Google Play Store, so Android 12 should be included.

**Comment by martijn00** [comment]
I thought Exoplayer targets 33: https://github.com/google/ExoPlayer/blob/release-v2/constants.gradle#L26

**Comment by ArchangelWTF** [comment]
Indeed it seems to, however there seems no impact if we target 33 or 32, so I've made my branch target both 32 and 33, as well as 33 for NET7
