### ISSUE TITLE
Add guava dependency

### ISSUE THREAD

**Issue by jerry08** [Baseflow/ExoPlayerXamarin#133]
It would be great to add google guava dependency to ExoPlayer.Core because when initializing a new instance of the playerview, it will crash without that library. Adding the nuget package separately will work. Those who aren't aware of adding guava to their projects will encounter problems.

**Comment by ArchangelWTF** [comment]
It's definitively possible, although considering when moving to the newext ExoPlayer version I already added Guava to ExoPlayer.Common https://github.com/Baseflow/ExoPlayerXamarin/commit/6aa6b2cbd85bd0b08984ce9de1805b5cd07434c9 and I thought it would just propagate to the other projects.. I assume that isn't the case however?

**Comment by jerry08** [comment]
Sorry, my bad. I just rechecked it and it works for nuget. Since the nuget packages weren't updated, I rebuilt the ExoPlayer project and referenced all the libraries in the output folder but doing that does not include the package references so I had to add them manually. The nuget pacakge takes care of them automatically. I'm patiently waiting for the update.
