### ISSUE TITLE
'SimpleCache' does not contain a constructor  that takes 3 arguments

### ISSUE THREAD

**Issue by ScriptSun** [Baseflow/ExoPlayerXamarin#136]
## 🐛 Bug Report

Error CS1729	'SimpleCache' does not contain a constructor that takes 3 arguments
We are not able to write a new SimpleCache function its always the same error.

Devs should be able to write this code bellow
var cache = new SimpleCache(new File(MainContext.CacheDir, "/toro_cache"), new LeastRecentlyUsedCacheEvictor(200 * 1024 * 1024), new ExoDatabaseProvider(MainContext));

Error
Error CS1729	'SimpleCache' does not contain a constructor that takes 3 arguments.

### Configuration

**Version:** 2.18.3

**Platform:** 
Android

**Comment by ArchangelWTF** [comment]
Does this still appear in 2.18.6? If so do you have a sample project so I can test it?

**Comment by jerry08** [comment]
This doesn't appear in the latest version. I've tested it and it works.
