### ISSUE TITLE
Expose DataSource.Factory.CreateDataSource()

### ISSUE THREAD

**Issue by sschaub** [Baseflow/ExoPlayerXamarin#142]
## 🏗 Enhancement Proposal

`DataSource.Factory.CreateDataSource()` is not exposed in the current bindings.

### Pitch

This is an important method used by frameworks such as XamarinMediaManager.

**Comment by martijn00** [comment]
@sschaub I merged it but the other extensions don't compile with this change. Can you fix that so i can make a release?

**Comment by sschaub** [comment]
My apologies, @martijn00, for breaking the build. I made a newbie assumption that turned out to be wrong. I think I've corrected it.

**Comment by sschaub** [comment]
> Does it work properly in XamarinMediaManager with your binding changes?

With this change, I was able to create a build of XamarinMediaManager that works for XF 5.

**Comment by martijn00** [comment]
I've fixed the last errors now and pushed some other changes. New version is online at nuget. I'll push this to MediaManager too, not sure if it works after that...
