### ISSUE TITLE
Support for Media3?

### ISSUE THREAD

**Issue by FreakyAli** [Baseflow/ExoPlayerXamarin#148]
## 💬 Questions and Help

Hi Guys, 

There is a new Support library for Media uses called Media3 available for Exoplayer, 
Are you guys planning to add those? Is this already available?

Thanks for the awesome bindings <3 

For questions or help we recommend checking:

**Comment by ArchangelWTF** [comment]
Considering Media3 is a AndroidX library I'll be surprised if Microsoft themselves don't eventually end up binding it, That being said Media3 seems to be pretty much Exoplayer but with it's name changed so I'm curious as to what's different.

I would suggest opening a issue here: https://github.com/xamarin/AndroidX though seeing as media2(https://github.com/xamarin/AndroidX/issues/268) has been open for quite some time now it'll still take some time for them to catch up.

**Comment by FreakyAli** [comment]
@ArchangelWTF OMG this is gonna take forever :( Anyway thanks for your help brother.
