### ISSUE TITLE
MonoAndroid bindings issues: IMediaSourceFactory and DownloadService

### ISSUE THREAD

**Issue by ivs88** [Baseflow/ExoPlayerXamarin#150]
## 🔙 Regression

Hi, I've found couple issues in the latest MonoAndroid 12.0 build [2.18.9](https://www.nuget.org/packages/Xamarin.Plugins.Android.ExoPlayer/2.18.9)

1. Media source factory classes (DefaultMediaSourceFactory, ProgressiveMediaSource.Factory, etc) don't implement IMediaSourceFactory interface. So you can't properly initialize ExoPlayer.
2. I've tried to use DownloadService and it throws excpetion "has no zero argument constructor". I'm not sure what's wrong, tried all variations of constructors with no luck. To reproduce this you can subclass DownloadService, add dummy implementation for missing members, add default constructor and call StartService().
3. DownloadService is missing [ACTION_RESTART constant](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/offline/DownloadService.java#L56)
4. Not sure if this is an issue, WorkManager latest package version is [2.18.8](https://www.nuget.org/packages/Xamarin.Plugins.Android.ExoPlayer.Workmanager/2.18.8), should it also be 2.18.9?

### Reproduction steps

For 1 just try to create ExoPlayer instance and call SetMediaSourceFactory()

For 2 here is a sample service

    [Service]
    public class TestDownloadService : DownloadService
    {
        private const int NOTIFICATION_ID = 1000002;
        protected override IScheduler Scheduler { get; }
        protected override DownloadManager DownloadManager { get; }

        public TestDownloadService() : base(NOTIFICATION_ID)
        {
        }

        protected override Notification GetForegroundNotification(IList<Download> downloads, int notMetRequirements)
        {
            return null;
        }
    }

**Version:** 2.18.9

**Platform:** 
- [ ] :robot: Android

**Comment by martijn00** [comment]
The nuget you are referencing is not an official nuget by me. Also MonoAndroid is deprecated.

**Comment by ivs88** [comment]
> The nuget you are referencing is not an official nuget by me. Also MonoAndroid is deprecated.

@martijn00 Sorry, I saw recent activity in #145 and thought it's a good place. But FYI: I think issues 2 and 3 are also happening in your nuget.

@janwiebe-jump do you have any plans on supporting MonoAndroid? If yes, could you take a look on issues above?

**Comment by martijn00** [comment]
https://www.nuget.org/packages/Xam.Plugins.Android.ExoPlayer/2.18.9-xamarin.1

I've added a Xamarin based nuget too now. Please open a PR to fix any binding errors so i can update this.

**Comment by ivs88** [comment]
@martijn00 Thanks, I've tried 2.18.9-xamarin.1 and it has same issues I've described above (exept WorkManager package version, removed that from description). Would you like to reopen this ticket?

**Comment by martijn00** [comment]
I have no time to work on fixing this myself, but am open to PR's. Please open one for this, or maybe @janwiebe-jump or @ArchangelWTF can do it?

**Comment by ivs88** [comment]
I figured out the 2nd, it turns out that missing constructor is a general xamarin bindings limitation and the workaround would be to use ExportAttribute
https://learn.microsoft.com/en-us/xamarin/android/internals/limitations#missing-constructors

**Comment by jonathanantoine** [comment]
Hello, this issue is now still happening on the official monodroid package ?
Can it be re opened ?

**Comment by jonathanantoine** [comment]
@martijn00 I have made a Pull request but I am not sure if I have to bump the version.

https://github.com/Baseflow/ExoPlayerXamarin/pull/182
