### ISSUE TITLE
Showing subtitle on Exoplayer (Leanback)

### ISSUE THREAD

**Issue by isaranghi** [Baseflow/ExoPlayerXamarin#151]
## 💬 Questions and Help

Hello,

Previously I was using Xam.Plugins.Android.ExoPlayer.Leanback version 2.11.8. I was able to load the subtitles using the following code

`      var subtitleView = RequireActivity().FindViewById(Resource.Id.leanback_subtitles) as SubtitleView;

        var style = new CaptionStyleCompat(
            Color.White,
            Color.Transparent,
            Color.Transparent,
            CaptionStyleCompat.EdgeTypeDropShadow,
            Color.Black,
            Typeface.Default!);

        var subtitleSize = GlobalSettings.GetFloat(GlobalSettings.KeySubtitleSize);

        if (subtitleSize != null)
        {
            subtitleView?.SetFixedTextSize((int)ComplexUnitType.Sp, subtitleSize.Value);
        }

        subtitleView?.SetApplyEmbeddedStyles(false);
        subtitleView?.SetStyle(style);

        if (subtitleView != null)
        {
            var textComponent = _player.TextComponent;
            textComponent.AddTextOutput(subtitleView);
        }

`

Now after upgrading to version 2.18.9 I am not able to call `textComponent.AddTextOutput(subtitleView);` Seems like AddTextOutput function isn't available anymore. Can anyone please help how can I make subtitles work.

Thanks

**Comment by isaranghi** [comment]
Based on some of the online samples, subtitleView.SetCues(cueGroup.cues) should do the trick. But I can't seem to find cues proeprty on CueGroup class. Is it somehting that's missed?

**Comment by ArchangelWTF** [comment]
2.11.8 seems very outdated considering we're on 2.18.* now, think you could update to 2.18 for MAUI or XF? (2.18-xamarin)

**Comment by isaranghi** [comment]
Thank you very much for your response but I don't think this issue is closed. Based on the similar answer for ExoPlayer (https://github.com/google/ExoPlayer/issues/9805), you can see that I should be able to do this 

`
    public void OnCues(CueGroup cueGroup)
    {
        _subtitleView.SetCues(cueGroup.cue);
    }
`

But there is no property cue available. I think that CueGroup should publicaly expose a List<Cue>

![image](https://user-images.githubusercontent.com/19824336/217843134-cb945e0b-e057-488e-8052-6755a11c9fab.png)

**Comment by isaranghi** [comment]
@martijn00 I think we should re-open this issue :)

**Comment by ArchangelWTF** [comment]
@isaranghi Since you did not provide a full sample, could you compile https://github.com/ArchangelWTF/ExoPlayerXamarin/tree/cues_fix this and see if Cues() will work for you?

**Comment by ArchangelWTF** [comment]
@isaranghi Did you manage to get this working yet?

**Comment by isaranghi** [comment]
@ArchangelWTF yes it worked with the List<Cue> exposed and setting it by calling subtitleView.SetCues. Would you be able to merge your changes and update the nuget package?
