### ISSUE TITLE
Where is DefaultUriDataSource?

### ISSUE THREAD

**Issue by mr5z** [Baseflow/ExoPlayerXamarin#89]
## 💬 Questions and Help

I usually rely on Visual Studio quick fix feature but it doesn't work this time for `DefaultUriDataSource`.
There are samples I can find on the web but they don't provide which namespace that type belongs.

**Comment by mr5z** [comment]
It seems it was named differently:`Com.Google.Android.Exoplayer2.Upstream.DefaultDataSource`.

**Comment by OdetteP** [comment]
Did you fix this issue?

**Comment by mr5z** [comment]
@OdetteP yeah but I used different types (the alternative I think is DefaultDataSource). I stopped following the official docs but follow that one from stackoverflow instead.
