### ISSUE TITLE
Where is ExoDatabaseProvider?

### ISSUE THREAD

**Issue by mr5z** [Baseflow/ExoPlayerXamarin#90]
## 💬 Questions and Help

I was trying to implement a Download feature and realized some of the types I am using are marked obsolete. Following the newest approach, [they recommend](https://exoplayer.dev/downloading-media.html) me to use `ExoDatabaseProvider` but it's nowhere to be found here in your repository.

Is it unimplemented yet?
(They said it was on ExoPlayer2)

**Comment by iamlawrencev** [comment]
Any update on this?
