### ISSUE TITLE
Include ICY metadata classes

### ISSUE THREAD

**Issue by marufbd** [Baseflow/ExoPlayerXamarin#92]
### Com.Google.Android.Exoplayer2.Metadata namespace is missing ICY classes

Is there any reason its omitted from the binding.
I would really like to use the ICY metadata feature from exoplayer which requires those classes from here:
https://github.com/google/ExoPlayer/tree/release-v2/library/core/src/main/java/com/google/android/exoplayer2/metadata/icy

**Comment by martijn00** [comment]
Because the binding is not updated to 2.10.x yet.
